spring:
  application: travel-app
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, mappings
---
spring:
  config:
    activate:
      on-profile: des
---
spring:
  config:
    activate:
      on-profile: hml
---
spring:
  config:
    activate:
      on-profile: prd