FROM mysql:latest

#COPY ./docker-entrypoint.sh /docker-entrypoint.sh
#COPY ./init.sql /docker-entrypoint-initdb.d/

ENV MYSQL_DATABASE=travelapp
ENV MYSQL_USER=mysql
ENV MYSQL_PASSWORD=mysql
ENV MYSQL_ROOT_PASSWORD=mysql
ENV MYSQL_PORT=3306

#ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 3306
